docs/release.rst
pyproject.toml

Add release command docs

---

src/saltext/vmware/modules/vmc_security_groups.py
tests/unit/modules/test_vmc_security_groups.py

Added create function for security groups.
Added unit tests for create function.

Added create function for security groups and corresponding unit test

---

.github/workflows/test.yml
CHANGELOG.md
docs/release.rst

Some fixes for release docs.

---

src/saltext/vmware/modules/vmc_networks.py
tests/unit/modules/test_vmc_networks.py

Added update function and corresponding unit tests for vmc_networks module
Resolved conflicts for PR: [https://github.com/saltstack/salt-ext-modules-vmware/pull/77](url)

Added update function and corresponding unit tests for vmc_networks module

---

src/saltext/vmware/modules/vmc_security_groups.py
tests/unit/modules/test_vmc_security_groups.py

Resolved conflict for PR [https://github.com/saltstack/salt-ext-modules-vmware/pull/76](url)

Security groups update function and corresponding tests

---

tests/integration/modules/test_vmc_dhcp_profiles.py

Added integration tests for vmc_dhcp_profiles execution module. Update of 
https://github.com/saltstack/salt-ext-modules-vmware/pull/86

Added integration tests for vmc_dhcp_profiles execution module. Update of PR-86

---

src/saltext/vmware/modules/esxi.py
tests/integration/modules/test_esxi.py

Get ntp config

---

src/saltext/vmware/modules/esxi.py
src/saltext/vmware/states/esxi.py
tests/integration/conftest.py
tests/integration/modules/test_esxi.py
tests/integration/states/test_esxi.py

Manage users on ESXi hosts

---

src/saltext/vmware/modules/esxi.py
src/saltext/vmware/states/esxi.py
src/saltext/vmware/utils/common.py
tests/integration/conftest.py
tests/integration/modules/test_esxi.py
tests/integration/states/test_esxi.py

vmkernel adapter exec + state mods

---

src/saltext/vmware/modules/esxi.py
src/saltext/vmware/utils/connect.py
tests/unit/modules/test_esxi.py

ref: vrae-3239
Salt States are not applicable for this functionality.

ESXi Config back/restore/reset

---

docs/release.rst
noxfile.py
pyproject.toml
setup.cfg
tools/release.py

This brings a lot more automation to the release process.
I've updated the documentation to reflect the changes to the release process!
This also adds towncrier for changelog entries, so we need to start requiring changelog entries for almost every change.

One ish click deploy

---

src/saltext/vmware/modules/esxi.py
src/saltext/vmware/states/esxi.py
src/saltext/vmware/utils/esxi.py
tests/integration/modules/test_esxi.py
tests/integration/states/test_esxi.py

add lockdown state and mod

---

docs/ref/modules/all.rst
docs/ref/modules/saltext.vmware.modules.vmc_vm_stats.rst
src/saltext/vmware/modules/vmc_vm_stats.py
src/saltext/vmware/utils/vmc_vcenter_request.py
tests/unit/conftest.py
tests/unit/modules/test_vmc_vm_stats.py
tests/unit/utils/test_vmc_vcenter_request.py

Added get function for vmc_vm_stats module and corresponding util and tests
Addressed the comments of PR [https://github.com/saltstack/salt-ext-modules-vmware/pull/83](url)

Added get function for vmc_vm_stats module and corresponding util and tests. Update of PR83

---

tests/integration/modules/test_vmc_networks.py

Added integration tests for vmc_networks execution module

Added integration tests for vmc_networks execution module

---

tests/integration/modules/test_vmc_dns_forwarder.py

Added integration tests for vm_dns_forwarder execution module

Added integration tests for vm_dns_forwarder execution module

---

tests/integration/modules/test_vmc_nat_rules.py
tests/unit/modules/test_vmc_nat_rules.py

Added integration tests for vmc nat rules.
Added one unit test for missing test.

vmc nat rules module it tests update of PR87

---

src/saltext/vmware/modules/vmc_distributed_firewall_rules.py
tests/unit/modules/test_vmc_distributed_firewall_rules.py

Added corresponding unit tests

Added get_by_id and delete function for distributed firewall rules

---

docs/ref/states/all.rst
docs/ref/states/saltext.vmware.states.vmc_nat_rules.rst
src/saltext/vmware/modules/vmc_nat_rules.py
src/saltext/vmware/states/vmc_nat_rules.py
tests/integration/modules/test_vmc_dns_forwarder.py
tests/integration/modules/test_vmc_nat_rules.py
tests/integration/modules/test_vmc_networks.py
tests/unit/modules/test_vmc_nat_rules.py
tests/unit/states/test_vmc_nat_rules.py

Added parameterized tests for present state (update and create) scenarios.

Added states file for vmc nat rules and unit tests. Update of PR85

---

tests/integration/modules/test_vmc_dhcp_profiles.py
tests/integration/modules/test_vmc_nat_rules.py
tests/integration/modules/test_vmc_networks.py
tests/integration/modules/test_vmc_security_rules.py

Fix for vmc test failures - Issue - 218

---

docs/ref/modules/all.rst
docs/ref/modules/saltext.vmware.modules.vmc_vcenter_stats.rst
src/saltext/vmware/modules/vmc_vcenter_stats.py
tests/integration/conftest.py
tests/integration/modules/test_vmc_vcenter_stats.py
tests/unit/modules/test_vmc_vcenter_stats.py
tools/test_value_scraper_vmc.py

Added execution module and corresponding unit tests for vm_vcenter_stats

Added vmc-vcenter-stats execution module and corresponding unit tests

---

docs/ref/states/all.rst
docs/ref/states/saltext.vmware.states.vmc_dhcp_profiles.rst
src/saltext/vmware/states/vmc_dhcp_profiles.py
src/saltext/vmware/utils/vmc_request.py
src/saltext/vmware/utils/vmc_state.py
tests/integration/modules/test_vmc_networks.py
tests/unit/states/test_vmc_dhcp_profiles.py

Worked on the review comments mentioned on PR: `https://github.com/saltstack/salt-ext-modules-vmware/pull/84`

State module for vmc_dhcp_profile. Update of PR 84

---

tests/integration/modules/test_vmc_dhcp_profiles.py
tests/integration/modules/test_vmc_networks.py

updated integration tests for vmc_networks and vmc_dhcp_profiles execution module

Fix for Issue 225 - updated tests

---

docs/ref/states/all.rst
docs/ref/states/saltext.vmware.states.vmc_networks.rst
src/saltext/vmware/states/vmc_networks.py
tests/integration/states/test_vmc_networks.py
tests/unit/states/test_vmc_networks.py

Added state module and corresponding unit tests for vmc_network

Added state module and corresponding unit tests for vmc network 

---

tests/integration/states/test_vmc_dhcp_profiles.py

Added integration tests for dhcp state module

Added integration tests for dhcp state module

---

tools/test_value_scraper_vmc.py

This change makes the VMC scraper read the config file first, so when doing
things like just changing the SDDC ID, only the one parameter has to be
provided.

improve scraper

---

src/saltext/vmware/states/license_mgr.py

Fixups of arguments and formats for license_mgr state docs

[DOCS] Fix state license mgr docs

---

src/saltext/vmware/modules/vm.py
src/saltext/vmware/states/vm.py

- Add examples for vmware_vm execution module
- Add examples for vmware_vm state module
- Update parameter documentation for `retry_delay` in `vmware_vm.boot_manager`

[DOCS] Update vmware_vm docs to add examples and fix bad parameters

---

src/saltext/vmware/modules/nsxt_compute_manager.py

Fix example for nsxt_compute_manager.get

[DOCS] Fix example for nsxt_compute_manager.get

---

src/saltext/vmware/modules/cluster_drs.py

- Fix example for vmware_cluster_drs.get
- Add example for vmware_cluster_drs.vm_affinity_rule
- Add example for vmware_cluster_drs.rule_info

[DOCS] Cleanup `vmware_cluster_drs` examples and add missing ones

---

src/saltext/vmware/states/datacenter.py

- Fix indentation on vmware_datacenter examples

[DOCS] Fix indentation on vmware_datacenter examples

---

src/saltext/vmware/modules/vswitch.py

- Add examples to vswitch execution module

[DOCS] Add examples to vswitch execution module

---

docs/quickstart.rst

doc(quickstart): restored original example IP because I didn't know TEST-NET-3 was a thing

Quickstart:  Restored original example IP

---

src/saltext/vmware/utils/connect.py

Handles issue
https://github.com/saltstack/salt-ext-modules-vmware/issues/126

new error when si cant be created

---

.github/workflows/test.yml
.pre-commit-config.yaml
noxfile.py
setup.cfg
src/saltext/vmware/modules/cluster.py
src/saltext/vmware/modules/cluster_drs.py
src/saltext/vmware/modules/cluster_ha.py
src/saltext/vmware/modules/datacenter.py
src/saltext/vmware/modules/datastore.py
src/saltext/vmware/modules/dvswitch.py
src/saltext/vmware/modules/esxi.py
src/saltext/vmware/modules/folder.py
src/saltext/vmware/modules/license_mgr.py
src/saltext/vmware/modules/vm.py
src/saltext/vmware/modules/vswitch.py
src/saltext/vmware/states/datastore.py
src/saltext/vmware/states/esxi.py
src/saltext/vmware/states/folder.py
src/saltext/vmware/states/vm.py
tests/unit/modules/test_esxi.py

The refactoring performed here was a suggestion made during the test clinic to make the `get_service_instance` calls consistent and improve the readability of the code a bit.
@waynew This is ready for review now

Refactored service_instance

---

README.md

Updated the README.md to add additional steps that I found were missing from the instructions in order to successfully access the vCenter

Update README.md to include instructions for required missing steps

---

.pre-commit-config.yaml
changelog/332.added
changelog/332.fixed
changelog/332.removed
src/saltext/vmware/modules/esxi.py
src/saltext/vmware/returners/merge_changes.py
src/saltext/vmware/returners/merge_changes_esxi.py
src/saltext/vmware/states/esxi.py
src/saltext/vmware/utils/esxi.py
tests/integration/modules/test_esxi.py
tests/unit/states/test_esxi.py

This is a replacement for #321 . Now pointing to fixed branch instead of main/test

CoE initial ESXi and drift_report

---

src/saltext/vmware/modules/esxi.py
src/saltext/vmware/utils/esxi.py
tests/unit/modules/test_esxi.py

Call get desired configuration ready
Implement get configuration and get desired configuration execution modules
Fix on get configuration and get desired configuration return
Add get configuration and get desired configuration documentation

Get configuration and get desired configuration using config modules

---

src/saltext/vmware/modules/esxi.py
tests/unit/modules/test_esxi.py

Updated with the tests and documentation for execution module

Jruta unified config

---

.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/test_publish.yml
noxfile.py
requirements/build.txt

Testing and updating ability to release

Modernized the noxfile and added a proto-release github action
